[program:test_paper_check]
command=bash -c "source /python_env/LLM_yyq/bin/activate && streamlit run /python_project/tecent_case_evaluate/test_paper_verification.py"
directory=/python_project/tecent_case_evaluate
priority=998
autostart=true
autorestart=false
stderr_logfile=/python_project/tecent_case_evaluate/Logging/supervisor_error.log
stdout_logfile=/python_project/tecent_case_evaluate/supervisor_print.log
#user=root